# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Obtain likelihood estimates of gappy Gaussian time series
#' 
#' Obtain likelihood of gappy standardized Gaussian time series "x" sampled at
#' times "t" given parameter "rho" (autocorrelation).  Alternatively computes
#' the characteristic time scale "tau".
#' 
#' @name GetL
#' 
#' @param x Time series
#' @param t Sampling times
#' @param rho Auto-correlation
#' @param tau logical: Whether or not to compute characteristic time scale
#' instead of rho.
#' @return Returns the log-likelihood of the data.
#' @author Eliezer Gurarie
#' @seealso Core function of BCPA, used directly in \code{\link{GetRho}}
#' @example examples/GetLExamples.R
NULL

GetL <- function(x, t, rho, tau = FALSE) {
    .Call('_bcpa_GetL', PACKAGE = 'bcpa', x, t, rho, tau)
}

